#!/usr/bin/python3

import amulet
import requests

seconds = 90000

d = amulet.Deployment(juju_deployer='juju-deployer -d -v', series='trusty')

d.add('thruk-master')
d.add('thruk-agent', charm='lp:~brad-marshall/charms/trusty/thruk-agent/trunk')
d.add('nagios')

d.relate('nagios:juju-info', 'thruk-agent:general-info')
d.relate('thruk-master:thruk-agent', 'thruk-agent:thruk-agent')

d.expose('thruk-master')

try:
    d.setup(timeout=seconds, cleanup=False)
    d.sentry.wait(timeout=seconds)
except amulet.helpers.TimeoutError:
    amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
except:
    raise

##
# Set relationship aliases
##
thruk_unit = d.sentry.unit['thruk-master/0']

try:
    thrukpwd = thruk_unit.file_contents('/var/lib/thruk/thrukadmin.passwd').strip()
except:
    raise

host_url = ("http://%s/thruk/")
try:
    r = requests.get(host_url % thruk_unit.info['public-address'],
                     auth=('thrukadmin', thrukpwd))
except:
    raise
