#!/usr/bin/python3

import amulet
import requests

seconds = 20000

d = amulet.Deployment(series='trusty')

d.add('thruk-master')

d.expose('thruk-master')

try:
    d.setup(timeout=seconds)
    d.sentry.wait()
except amulet.helpers.TimeoutError:
    amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
except:
    raise

##
# Set relationship aliases
##
thruk_unit = d.sentry.unit['thruk-master/0']

thrukpwd = thruk_unit.file_contents('/var/lib/thruk/thrukadmin.passwd').strip()

host_url = ("http://%s/thruk/")
r = requests.get(host_url % thruk_unit.info['public-address'],
                 auth=('thrukadmin', thrukpwd))

